### ISSUE TITLE
Tree structure support

### ISSUE THREAD

**Issue by JulienNexonia** [500tech/angular2-tree-component#110]
Hi,
I am wondering if there are any plans to support the tree structure (https://two-wrongs.com/draw-a-tree-structure-with-only-css)

I tried to set up such a structure by styling the tree as follows: 
```
.node-content-wrapper, .tree-children {
  position: relative;
}

.node-content-wrapper {
  list-style: none;
}

.node-content-wrapper::before, .tree-children::after {
  content: "";
  position: absolute;
}

.node-content-wrapper::before {
  border-top: 1px solid lightgrey;
  top: 10px;
  width: 20px;
  height: 0;
  left: -27px;
}

.tree-children::after {
  border-left: 1px solid lightgrey;
  height: 100%;
  width: 0px;
  top: 0px;
  left: 5px;
  margin-top: -15px;
}

.toggle-children-placeholder {
  padding-bottom: 14px;
}

.treenode:last-child {
  background-color: red;
}

.toggle-children {
  z-index: 1;
}

```

The main problem I still have is that I am unable to refer to the last-child to stop the vertical line of the tree.

The red selection shows where the lines should be stopped.
![01](https://cloud.githubusercontent.com/assets/2727742/20652833/6752634a-b555-11e6-9e08-d04da099965e.png)

Any help would be appreciated !
Thanks !
Julien

**Comment by adamkleingit** [comment]
You need to use
`treenode:last-child { }`
instead of 
`.treenode:last-child { }`

**Comment by adamkleingit** [comment]
There you go!

```css

.node-content-wrapper, .tree-children {
  position: relative;
}

.node-content-wrapper::before, .tree-children::after {
  content: "";
  position: absolute;
}

.node-content-wrapper::before {
  border-bottom: 1px solid lightgrey;
  border-left: 1px solid lightgrey;
  height: 28px;
  top: -17px;
  width: 20px;
  left: -28px;
}

.tree-node-leaf > .node-wrapper > .node-content-wrapper::before {
  width: 25px;
}

.tree-children::after {
  border-left: 1px solid lightgrey;
  height: 100%;
  top: -15px;
  left: -15px;
}

treenode:last-child > .tree-node > .tree-children::after {
  border-left: none;
}

.toggle-children {
  z-index: 1;
}

```
