### ISSUE TITLE
Change icons

### ISSUE THREAD

**Issue by ciesielskico** [500tech/angular2-tree-component#56]
I'm using Material Icons all over my app and was wondering if I could use them on the tree-component, too?

I'm talking about chevron left+right, and expand less+more

https://design.google.com/icons/#ic_chevron_left

**Comment by isaacplmann** [comment]
You could do something like this:

1. Download the svg for the chevron-right icon. `ic_chevron_right_black_24px.svg`
2. Add a `material-design` class to a wrapper around the tree.
3. Add this css:

```css
.material-design .toggle-children {
  background-image: url('path/to/assets/ic_chevron_right_black_24px.svg');
}
```
